### ISSUE TITLE
Unable to record when .mp4 video embedded. Only .webm format is working. 

### ISSUE THREAD

**Issue by rana01645** [tungs/timecut#19]
Thanks for the awesome library.

Recording of .mp4 embeds not working.
 It's giving an error like "PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS"

Could you please tell me how to fix it

**Comment by tungs** [comment]
By default, timecut installs and uses Chromium to capture screenshots. Chromium doesn't support `.mp4`, but Chrome does. If you want to use Chrome instead, you can install it, and then use --executable-path/config.executablePath configuration option to point to the version of Chrome you want to use.

**Comment by rana01645** [comment]
Great.. it helped me :dagger: Thank you soo much.
