### ISSUE TITLE
Option to use jsdom or node-canvas instead of url

### ISSUE THREAD

**Issue by attachaudhury** [tungs/timecut#25]
I am wondering that if there is any available option to use timecut with [node-canvas](https://github.com/Automattic/node-canvas) or [jsdom](https://github.com/jsdom/jsdom) instead of url option.

**Comment by tungs** [comment]
Thanks for asking this question! I'm not quite sure if I understand. What is your use case? timecut is aimed to make videos of webpages that run in web browsers, while from my understanding node-canvas or jsdom are used inside node programs.

**Comment by attachaudhury** [comment]
> Thanks for asking this question! I'm not quite sure if I understand. What is your use case? timecut is aimed to make videos of webpages that run in web browsers, while from my understanding node-canvas or jsdom are used inside node programs.

node-canvas can be used in node backend for rendering svgs (then this svgs can be saved as images/buffers) also we can animate the canvas objects in node-canvas. My point is how can we use  node-canvas(generated images/buffers) with timecut, This can reduce timecut http requests made for capturing screen shoots of a website.

**Comment by tungs** [comment]
Ahh, I think I understand now; you're suggesting to use node-canvas and js-dom as replacements to parts or all of puppeteer for rendering, correct? I'm not sure how that would cut down on http requests, unless you know what relevant parts of the web page to load.

If I'm understanding you correctly, it sounds like an interesting approach, but I think it's outside of the scope of this project, unless there are plugins to puppeteer that automatically do that.

**Comment by attachaudhury** [comment]
> correct

Yes that was my point.
