### ISSUE TITLE
Export to gif

### ISSUE THREAD

**Issue by hatemhosny** [tungs/timecut#29]
Great work. Thank you for sharing 

Any guidance on how to export to gif instead of video?

**Comment by tungs** [comment]
I'm not very familiar with using ffmpeg to create gifs, but from what I understand, a palette should be generated to be space efficient. The way I've done it is to first use `timecut` to create an mp4, then to use ffmpeg to create a palette from the mp4, and then to convert that mp4 to a gif.

The commands would be something like:

```
timecut "index.html" --output=video.mp4
ffmpeg -i video.mp4 -filter_complex "[0:v] palettegen" palette.png
ffmpeg -i video.mp4 -i palette.png -filter_complex "[0:v][1:v] paletteuse" video.gif
```

1. The first command captures a video using timecut of `index.html` and saves it `video.mp4`.
2. The second generates a palette for the gif conversion to use, and saves it to `palette.png`
3. The third converts the video using the previously saved palette, and saves the gif to `video.gif`

This is a very basic way to do it. There are many more sophisticated guides on the internet to covert mp4s to gifs. Also see [timesnap](https://github.com/tungs/timesnap) if you're looking to work with individual, higher quality frames.

**Comment by hatemhosny** [comment]
Thank you 🙏
