### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by codler** [tungs/timecut#30]
Timecut version 0.1.2

```
npm i timecut
node node_modules/timecut/cli.js https://google.com
```

```
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-framerate',
    30,
    '-i',
    '/Users/x/image-%09d.png',
    '-pix_fmt',
    'yuv420p',
    '-y',
    '/Users/x/video.mp4'
  ]
}
```
Do you know what this error means?

**Comment by tungs** [comment]
Hi @codler, thanks for filing this! Do you have ffmpeg installed? I think the ENOENT (no such file or directory) error can arise from that.

**Comment by codler** [comment]
aha I thought `npm i timecut` would install ffmpeg. How do I install ffmpeg on mac?

**Comment by tungs** [comment]
I don't use ffmpeg on a mac, so my experience is pretty light on this. However, there are plenty of guides online to install ffmpeg on a mac. Just make sure that the `ffmpeg` command is available from the command line.

**Comment by codler** [comment]
Thanks, after installing ffmpeg it worked.

```
brew install ffmpeg

**Comment by florinvirdol** [comment]
Hi,
Are there any examples of how to install and set ffmpeg path on Windows 10, please?!
Thank you!
