### ISSUE TITLE
Capturing hangs after some frames 

### ISSUE THREAD

**Issue by danish-pyxis** [tungs/timecut#33]
Promise in timesnap 
`p = timeHandler.goToTimeAndAnimateForCapture(browserFrames, marker.time);`

does not get resolved after some frames and puppeteer hangs infinitely.

As a workaround, I have used a timeout to detect unhandled promise but its letting me destroy that process.

Can we discuss - why is this odd behaviour?

**Comment by tungs** [comment]
Does this happen for all webpages? If it's for a specific web page, could you post it?

**Comment by tungs** [comment]
Let's move the discussion over to tungs/timesnap#41, since that's likely where the issue originates
