### ISSUE TITLE
Doesn't work with anime.js

### ISSUE THREAD

**Issue by varunarora** [tungs/timecut#4]
I am using a pretty standard and popular animation library called `anime.js`. The animations don't seem to render. Am I doing something fundamentally wrong? Or is the library non-standard?

**Comment by tungs** [comment]
Looks like that the code in `timecut`/`timesnap` that overwrites `requestAnimationFrame` isn't passing a time value to the callback. It seems that anime.js relies on that time value. I'll work on a fix this week. Thanks for filing this issue! 

For more information about `requestAnimationFrame`: 
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames

**Comment by tungs** [comment]
Should be fixed in tungs/timesnap@7f2cbfd24084e59738c18a5a8b87f53598b21cda and da3a52a5cadc98f18cf52a1ab915715f7eef1b27 (and in v0.0.3). Please let me know if the new version still doesn't work. Thanks!

**Comment by varunarora** [comment]
Oh awesome let me give this a shot!

**Comment by varunarora** [comment]
WORKS! So excited! Thanks.

**Comment by tungs** [comment]
Awesome! Glad that it works. Thanks for filing this!
