### ISSUE TITLE
can not capture frames playing-in-canvas

### ISSUE THREAD

**Issue by TejasBob** [tungs/timecut#54]
@tungs thank you for sharing this awesome project.

Following is the HTML file that I'm trying to record with headless Google-Chrome & timecut.

```
  <!-- <script  src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> -->
<html>
    <body>
  <div id="theater">
    <video 
        id="video" 
        src="file:///home/bob/BigBuckBunny2.mp4" 
        type="video/mp4"
        autoplay muted width=400 height=300>
    </video>
    <div>
      <canvas id="my-canvas" width=400 height=300 style="border: 10px solid red;"></canvas>
  </div>
    <label>
      <br />Try to play me :)</label>
    <br />
  </div>
  <script>
      function fn() {
        var canvas = document.getElementById('my-canvas');
        var ctx = canvas.getContext('2d');
        var video = document.getElementById('video');
        console.log("inside function\n");

        video.addEventListener('play', function() {
            var $this = this; //cache
            (function loop() {
            if (!$this.paused && !$this.ended) {
                ctx.drawImage($this, 0, 0);
                setTimeout(loop, 1000 / 30); // drawing at 30fps
            }
            })();
        }, 0);
        };
        fn();
  </script>
  </body>
  </html>
```
It looks like this on Desktop in Google Chrome.
![image](https://user-images.githubusercontent.com/10771892/120905721-a3d41780-c619-11eb-99c3-999650c40b99.png)

I'm using the following command to record the page. The recording happens in headless mode.
`timecut "file:///home/bob/test2.html" --viewport="1920,1080"  --executable-path="/usr/bin/google-chrome" --fps=25  --duration=5   --pipe-mode --pix-fmt=yuv420p --output=video.mp4
`

And the recording looks like this. Why nothing is being captured from the canvas element?

https://user-images.githubusercontent.com/10771892/120905985-74260f00-c61b-11eb-8d0e-07ad6e70b6e5.mp4

I'm on Ubuntu 16.04 LTS, using Chrome Version 90.0.4430.212 (Official Build) (64-bit).
I'm using the same chrome binary for headless recording.
Node Version  v15.2.0
Timecut Version 0.2.0
BigBuckBunny mp4 file available at [http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4](BigBuckBunny.mp4)

Why nothing is being captured from the canvas element? What am I missing here?

**Comment by TejasBob** [comment]
Never mind, I think I figured it out.
Adding `video.play()` in `fn()` helped me get the expected output.
But it's quite surprising that the same Chrome binary is behaving differently in Desktop mode and automation (controlled through Puppeteer) mode.

**Comment by tungs** [comment]
Hi @TejasBob, thanks for filing this!

`timecut` (and its underlying library `timeweb`) alter the default behavior of media elements, so it could be it is responsible for this issue.

In this case, it looks like the original issue stems from an attached event listener not receiving the `play` event from an autoplayed video. `timeweb` immediately dispatches the `play` event for autoplayed media, probably before your listener is attached. I'm not sure if this is technically right, though even if it is, it would be more user friendly if it delays dispatching the event until listeners have a chance to be attached.

I've opened an issue at tungs/timeweb#1, which should be the right place for it.

**Comment by TejasBob** [comment]
Yes, that makes sense.
Thank you for providing explanation.
In this specific case, it would be cleaner to do following,

1. remove `autoplay` and `muted` attributes from HTML `video` tag
2. add "play" `eventListener` in JS
3. set the `autoplay` and `muted` attributes in JS

This way I'm making sure `eventListener` is attached before playing the video.
It works consistently after doing these changes.
Appending updated file for reference.

And it will be interesting to find out following @ [tungs/timeweb#1](https://github.com/tungs/timeweb/issues/1#issue-912917261)

> There's an underlying question of when the play event should be dispatched on autoplayed media. It would be interesting to investigate what spec says, and how current browsers implement this.


Update file:
```
<html>
    <body>
  <div id="theater">
    <video 
        id="video" 
        src="file:///home/bob/BigBuckBunny2.mp4" 
        type="video/mp4"
        width=400 height=300>               <!-- removed autoplay and muted from here -->
    </video>
    <div>
      <canvas id="my-canvas" width=400 height=300 style="border: 10px solid red;"></canvas>
  </div>
    <label>
      <br />Try to play me :)</label>
    <br />
  </div>
  <script>
      function fn() {
        var canvas = document.getElementById('my-canvas');
        var ctx = canvas.getContext('2d');
        var video = document.getElementById('video');
        console.log("inside function\n");

        video.addEventListener('play', function() {
            var $this = this; //cache
            (function loop() {
            if (!$this.paused && !$this.ended) {
                ctx.drawImage($this, 0, 0);
                setTimeout(loop, 1000 / 30); // drawing at 30fps
            }
            })();
        }, 0);
        video.muted = true;                   // this has changed
        video.autoplay = true;               // this has changed
        };
        fn();
  </script>
  </body>
  </html>
```

**Comment by tungs** [comment]
Yes, I think your updated file is a less ambiguous implementation and removes the possible race condition. If there should be a race condition, I think the event listener attachment always wins the race in normal webpages and most browsers, (since JavaScript runs synchronously, while video loads asynchronously), though `timeweb`'s implementation has the video winning the race in some cases. It may be that there shouldn't be a race, and that videos should dispatch events only after subsequently defined JavaScript code runs. I'm not sure about how strictly defined this behavior is; I'm not that familiar with spec, and it's worthwhile to look into.

I think delaying the play event dispatching in `timeweb` shouldn't break things in most cases, though there might be a case that I'm overlooking.
