### ISSUE TITLE
Video's animation seems faster than original animation in website

### ISSUE THREAD

**Issue by RechieKho** [tungs/timecut#58]
Just like the title said, the video rendered is much faster than the original animation open in the browser. I try to change settings but I have no idea what causes this. 
I tried to render the night animation (https://github.com/antonyleme/CSS-Animations) 
and this is the result (https://user-images.githubusercontent.com/50512341/124915006-e0db5300-dfa5-11eb-8fff-692b10e0e7a1.mp4)

The animation in the video ends up very fast. **Help**.

**Comment by Asheboy** [comment]
Hi @RechieKho.

As stated in the readme, https://github.com/tungs/timecut#limitations, it is only JavaScript timers which get overridden, so any CSS transitions/animations are not support. I've got around this before by using a JavaScript based animation library, like React Spring https://react-spring.io/.

**Comment by RechieKho** [comment]
So we can only animate by setting css property using javascript right? I need to use pure javascript or javascript library such as animejs instead of pure css right?

**Comment by Asheboy** [comment]
`I need to use pure javascript or javascript library such as animejs instead of pure css right?` - Correct.

**Comment by RechieKho** [comment]
Ok thanks.
