### ISSUE TITLE
Can you speedup the capture process by using multi pupeeter tabs ?

### ISSUE THREAD

**Issue by motniemtin** [tungs/timecut#59]
Can you speedup the capture process by using multi pupeeter tabs ?
I'm Vietnamese, Love your name !

**Comment by tungs** [comment]
Thanks for the interest and the idea @motniemtin. There have been some ideas of how to make capturing faster, with some apparent success, at #23 and tungs/timesnap#8, though I don't think anyone's mentioned or thought of multiple tabs. I'm not familiar with how puppeteer allocates resources to tabs; as far as I know, it might be useful or it might be a dead end. Feel free to leave a comment in the linked discussion threads, though as mentioned in those threads, I don't have a lot of time to personally work on or test this sort of issue.
