### ISSUE TITLE
[FEATURE REQUEST] Add option to use custom ffmpeg path

### ISSUE THREAD

**Issue by elbadryd** [tungs/timecut#61]
**Is your feature request related to a problem? Please describe.**
I am trying to use timecut with [node-ffmpeg installer](https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg). This proves to be problematic, as my desired ffmpeg path is contained within nodemodules, rather than installed on system binaries. 

**Describe the solution you'd like**
 I would like to be able to pass in a custom argument for ffmpegPath as a config value.

**Describe alternatives you've considered**

**Additional context**

**Comment by tungs** [comment]
Added in v0.3.3
