### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by gurugeek** [tungs/timecut#64]
Elapsed capture time: 75683
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-framerate',
    60,
    '-i',
    '/Users/gurugeek/Downloads/fishdraw-main/timecut-temp-1654480292749/image-%09d.png',
    '-pix_fmt',
    'yuv420p',
    '-y',
    '/Users/gurugeek/Downloads/fishdraw-main/video.mp4'
  ]
}
(node:57394) UnhandledPromiseRejectionWarning: Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
gurugeek@davids-imac fishdraw-main %

**Comment by florinvirdol** [comment]
I think the error appears because it doesn't find `ffmpeg` executable. 
I'm having a similar error when trying to run on Windows 10. 

Tried setting `ffmpegPath` to the `ffmpeg.exe` but without any luck.. 

Any ideas, please?! Thank you!
