### ISSUE TITLE
Can't render an animated SVG in slowmotion

### ISSUE THREAD

**Issue by fra3point** [tungs/timecut#69]
Hello!
I have an issue while recording an animated SVG. 

Pobably I'm just confused on how the "fps" and "duration" options really work.

My goal is to generate multiple PNG images (I use the `--keep-frames` option for this) representing the animation frames.

My first test was rendering a 64fps, 1s long video.

So I used `--fps 64 --duration 1`

Unfortunately, the animation was too fast so I decided to go for a 256fps, 4s long video. The result was just the same as before, but looped 4 times in sequence.

Just for test, I also tried rendering both a 64fps 4s video and a 256fps 1s video.... And they appear to be the same! 
I thought that the first would result in a 4 cycles loop (one per second), while the second would result in a single cycle rendered at a higher framerate.

Is there a way to get a slowmotion video out of an animated SVG?
Attached, you can find the SVG I used in my tests.

Thanks in advance!
![proactive_2_2](https://user-images.githubusercontent.com/34285897/198726908-93af076f-cb78-48a9-800b-6c0aa53b3998.svg)

**Comment by tungs** [comment]
Hi @fra3point, animated svgs aren't supported. See #39
