### ISSUE TITLE
animation in the reverse [BUG]

### ISSUE THREAD

**Issue by mtrud** [tungs/timecut#71]
The SVG animation is from left to right, but after saving the video the dots in the animation are going from right to left.
also the time of the animation is 4 seconds but in the video its much quicker

my command : `./node_modules/timecut/cli.js ex2.html --viewport="1280,720" --fps=24 --duration=5 \
  --frame-cache --pix-fmt=yuv420p --output=video3.mp4`

my file : https://github.com/mtrud/testings/blob/main/ex2.html  

 - OS: [Mac OS]
 - Timecut Version [v0.3.3]

**Comment by mtrud** [comment]
any help?

**Comment by tungs** [comment]
hi @mtrud, thanks for your interest in this library. SVG animations are not supported. See #39 for more information.

**Comment by tungs** [comment]
Just also wanted to add, thanks for bring this to my attention again! I reread #39, and realized I haven't gotten around to trying out implementations for SVGs.
