### ISSUE TITLE
Are you open for paid support?

### ISSUE THREAD

**Issue by videowala** [tungs/timecut#9]
@tungs Thanks a lot for developing this tool. We are planning to use it in our project but we have some specific requirements. 
I was wondering if you can offer paid support/feature development.
Sorry for filing issue for this but I could not another way to contact you.

**Comment by tungs** [comment]
Hi @videowala, thanks for getting in contact. I'm open to the idea of paid support/feature development, but it would depend on the scope and type of project. What would be a good way to contact you to find out more about your projects and requirements?

**Comment by videowala** [comment]
@tungs Thanks for the reply. Please send me an email at videowala19 at gmail dot com. We will take it forward from there.

**Comment by tungs** [comment]
@videowala, Thanks, I just sent an email. Let me know if you didn't get it.
